.

In [1]:
pip install cvxpy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: cvxpy in c:\users\hp\anaconda3\lib\site-packages (1.3.1)
Requirement already satisfied: osqp>=0.4.1 in c:\users\hp\anaconda3\lib\site-packages (from cvxpy) (0.6.2.post9)
Requirement already satisfied: ecos>=2 in c:\users\hp\anaconda3\lib\site-packages (from cvxpy) (2.0.12)

WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\hp\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\hp\anaconda3\lib\site-packages)

Requirement already satisfied: scs>=1.1.6 in c:\users\hp\anaconda3\lib\site-packages (from cvxpy) (3.2.3)
Requirement already satisfied: numpy>=1.15 in c:\users\hp\anaconda3\lib\site-packages (from cvxpy) (1.21.5)
Requirement already satisfied: scipy>=1.1.0 in c:\users\hp\anaconda3\lib\site-packages (from cvxpy) (1.7.3)
Requirement already satisfied: setuptools>65.5.1 in c:\users\hp\anaconda3\lib\site-packages (from cvxpy) (67.8.0)
Requirement already satisfied: qdldl in c:\users\hp\anaconda3\lib\site-packages (from osqp>=0.4.1->cvxpy) (0.1.7)

Import necessary libraries

In [2]:
import pandas as pd
import numpy as np
import random
import cvxpy as cp

In [3]:
df = pd.read_excel("../Datasets/cities.xlsx")

In [4]:
df.head(15)

          Name  Affected  Dist  Population
0     İstanbul         0     1    15462452
1       Ankara         0     1     5663322
2        İzmir         0     1     4394694
3        Bursa         0     1     3101833
4      Antalya         0     1     2548308
5        Adana         1     0     2258718
6        Konya         0     1     2250020
7    Şanlıurfa         1     0     2115256
8    Gaziantep         1     0     2101157
9      Kocaeli         0     1     1997258
10      Mersin         0     1     1868757
11  Diyarbakır         1     0     1783431
12       Hatay         1     0     1659320
13      Manisa         0     1     1450616
14     Kayseri         0     1     1421455

In [5]:
dist_centers = df[df["Dist"]==1]["Name"].str.title().to_list()
affected_cities = df[df["Affected"]==1]["Name"].str.title().to_list()

In [6]:
dist_centers

['İstanbul',
 'Ankara',
 'İzmir',
 'Bursa',
 'Antalya',
 'Konya',
 'Kocaeli',
 'Mersin',
 'Manisa',
 'Kayseri']

In [7]:
affected_cities

['Adana',
 'Şanlıurfa',
 'Gaziantep',
 'Diyarbakır',
 'Hatay',
 'Kahramanmaraş',
 'Malatya',
 'Adıyaman',
 'Elazığ',
 'Osmaniye',
 'Kilis']

Create distances matrix

In [8]:
distances = pd.read_excel("../Datasets/ilmesafe.xlsx")

In [9]:
distances

,Name,Adana,Adıyaman,Afyonkarahisar,Ağrı,Amasya,Ankara,Antalya,Artvin,Aydın,...,Batman,Şırnak,Bartın,Ardahan,Iğdır,Yalova,Karabük,Kilis,Osmaniye,Düzce
0,Adana,NaN,337.0,578.0,973.0,603.0,492.0,547.0,1001.0,880.0,...,628.0,712.0,784.0,1037.0,1077.0,905.0,714.0,251.0,89.0,735.0
1,Adıyaman,337.0,NaN,915.0,642.0,627.0,732.0,884.0,715.0,1217.0,...,297.0,464.0,1016.0,751.0,746.0,1137.0,946.0,210.0,244.0,966.0
2,Afyonkarahisar,578.0,915.0,NaN,1320.0,596.0,255.0,287.0,1224.0,340.0,...,1207.0,1290.0,518.0,1361.0,1464.0,346.0,449.0,830.0,667.0,371.0
3,Ağrı,973.0,642.0,1320.0,NaN,740.0,1055.0,1424.0,364.0,1634.0,...,365.0,424.0,1171.0,305.0,144.0,1363.0,1106.0,812.0,880.0,1192.0
4,Amasya,603.0,627.0,596.0,740.0,NaN,331.0,823.0,679.0,935.0,...,805.0,998.0,436.0,781.0,884.0,629.0,371.0,640.0,603.0,458.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Yalova,905.0,1137.0,346.0,1363.0,629.0,407.0,610.0,1238.0,507.0,...,1403.0,1549.0,373.0,1347.0,1507.0,NaN,351.0,1116.0,994.0,171.0
77,Karabük,714.0,946.0,449.0,1106.0,371.0,216.0,735.0,958.0,788.0,...,1174.0,1358.0,86.0,1067.0,1250.0,351.0,NaN,925.0,803.0,180.0
78,Kilis,251.0,210.0,830.0,812.0,640.0,711.0,798.0,885.0,1131.0,...,467.0,550.0,995.0,920.0,915.0,1116.0,925.0,NaN,159.0,945.0
79,Osmaniye,89.0,244.0,667.0,880.0,603.0,581.0,636.0,909.0,969.0,...,535.0,619.0,873.0,944.0,984.0,994.0,803.0,159.0,NaN,823.0
80,Düzce,735.0,966.0,371.0,1192.0,458.0,237.0,636.0,1067.0,688.0,...,1232.0,1378.0,202.0,1177.0,1336.0,171.0,180.0,945.0,823.0,NaN

In [10]:
# Create a new dataframe
new_df = pd.DataFrame(columns=distances.columns)

# Iterate over each row in the original dataframe
for index, row in distances.iterrows():
    if row['Name'] in dist_centers:
        # Append the row to the new dataframe
        new_df = new_df.append(row)

C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)
C:\Users\Hp\AppData\Local\Temp\ipykernel_8328\2085871676.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(row)

In [11]:
dist_centers

['İstanbul',
 'Ankara',
 'İzmir',
 'Bursa',
 'Antalya',
 'Konya',
 'Kocaeli',
 'Mersin',
 'Manisa',
 'Kayseri']

In [12]:
distance_df = new_df[affected_cities]

In [13]:
distance_df

,Adana,Şanlıurfa,Gaziantep,Diyarbakır,Hatay,Kahramanmaraş,Malatya,Adıyaman,Elazığ,Osmaniye,Kilis
5,492.0,786.0,647.0,898.0,688.0,572.0,652.0,732.0,749.0,581.0,711.0
6,547.0,902.0,763.0,1084.0,743.0,744.0,953.0,884.0,1051.0,636.0,798.0
15,856.0,1158.0,1020.0,1270.0,1052.0,944.0,1024.0,1104.0,1121.0,945.0,1083.0
32,70.0,424.0,286.0,606.0,265.0,267.0,466.0,407.0,564.0,159.0,321.0
33,951.0,1237.0,1098.0,1349.0,1147.0,1023.0,1103.0,1183.0,1200.0,1040.0,1162.0
34,907.0,1261.0,1123.0,1436.0,1102.0,1104.0,1190.0,1244.0,1287.0,995.0,1158.0
37,335.0,468.0,330.0,581.0,428.0,255.0,335.0,414.0,432.0,356.0,393.0
40,840.0,1127.0,988.0,1239.0,1036.0,913.0,993.0,1072.0,1090.0,929.0,1051.0
41,357.0,712.0,573.0,887.0,553.0,555.0,641.0,695.0,738.0,446.0,609.0
44,886.0,1240.0,1102.0,1415.0,1081.0,1083.0,1169.0,1223.0,1266.0,974.0,1137.0

In [14]:
distance_matrix = np.array(distance_df)

In [15]:
coefs_list = [int(i)/10 for i in range(10,0,-1)]

In [16]:
coefs_list

[1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]

In [17]:
truck = 500
helicopter = 10

In [18]:
trucks = [coefs_list[i]*truck for i in range(len(coefs_list))]

In [19]:
helicopters = [coefs_list[i]*helicopter for i in range(len(coefs_list))]

In [20]:
trucks

[500.0, 450.0, 400.0, 350.0, 300.0, 250.0, 200.0, 150.0, 100.0, 50.0]

In [21]:
helicopters

[10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0]

In [22]:
# helicopter_capacity = 10000
# truck_capacity = 20000

In [23]:
# helicopter_speed_coef = 250
# truck_speed_coef = 80

Objective Function
Minimize: Σ(c_i * x_i) -- This part represents the cost

Subject to: Σ(t_i * x_i) ≤ T_max --

Total erzak <br>
araçların kapasitesi: helikopter ve kamyon<br>
helikopter sayımız ve kamyon sayımız belli<br>
İstanbuldan çıkan bir kamyon<br>
Ankara 1000 erzak 50 kamyon 10 helikopter<br>
Bursa 1000 erzak 50 kamyon 10 helikopter<br>
Total erzak ihtiyaçtan fazla tanımlanacak

In [24]:
# Define the size of the matrix
rows = 10
cols = 11

# Define the number of blocked positions
num_blocked = 10

# Create an empty matrix
road_blocked = np.zeros((rows, cols), dtype=bool)

# Generate random blocked positions
blocked_positions = np.random.choice(rows * cols, size=num_blocked, replace=False)

# Mark the blocked positions as True
for position in blocked_positions:
    row = position // cols
    col = position % cols
    road_blocked[row, col] = True

In [25]:
road_blocked

array([[False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False,  True, False,
         True, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [ True,  True, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False],
       [False, False, False,  True, False, False, False, False, False,
        False, False],
       [False, False, False,  True, False, False, False, False, False,
        False, False],
       [False,  True, False, False,  True, False, False,  True, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False]])

In [26]:
MAX_HELICOPTER_CAPACITY = 20
HELICOPTER_SPEED = 200
MAX_TRUCK_CAPACITY = 50
TRUCK_SPEED = 100
HELICOPTER_NUMBER = 10
TRUCK_NUMBER = 500
NUM_DISTRIBUTION_CENTERS = 10
NUM_AFFECTED_CITIES = 11

demand_matrix = np.array([
[0.0, 0.0, 253.5677, 0.0, 0.0, 676.806, 615.8715, 0.0, 0.0, 0.0, 0.0],
[566.3322, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 147.194, 0.0, 0.0, 0.0, 292.2754, 0.0],
[310.1833, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 254.8308, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 225.002, 0.0],
[0.0, 0.0, 199.7258, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 186.8757, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[123.4845, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 21.5771, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 142.1455, 0.0]
])

In [27]:
print(sum(sum(demand_matrix)))

4015.8715

In [28]:
demand_matrix=demand_matrix.T

In [29]:
# Supplies of each distribution city
supplies = [1546.2452, 566.3322, 439.4694, 310.1833, 254.8308,
            225.002, 199.7258, 186.8757, 145.0616, 142.1455]

# Demand of each demand city
demands = [1000.0, 922.0, 895.0, 859.0, 838.0, 824.0,
           803.0, 783.0, 778.0, 681.0, 632.0]

# # Create a 2D list for truck transfers with random values
# truck_transfers = np.zeros((10, 11), dtype=int)
# for i in range(10):
#     for j in range(11):
#         truck_transfers[i][j] = np.random.randint(0, min(supplies[i], demands[j]) + 1)

# # Create a 2D list for helicopter transfers with random values
# helicopter_transfers = np.zeros((10, 11), dtype=int)
# for i in range(10):
#     for j in range(11):
#         helicopter_transfers[i][j] = np.random.randint(0, min(supplies[i], demands[j]) + 1)

In [ ]:
supplies = [1546.2452, 566.3322, 439.4694, 310.1833, 254.8308,
            225.002, 199.7258, 186.8757, 145.0616, 142.1455]

# Demand of each demand city
demands = [1000.0, 922.0, 895.0, 859.0, 838.0, 824.0,
           803.0, 783.0, 778.0, 681.0, 632.0]

In [31]:
def create_population(size, bounds):
    population = []
    for _ in range(size):
        # Create a 2D list for truck transfers with random values
        truck_transfers = np.zeros((10, 11), dtype=int)
        for i in range(10):
            for j in range(11):
                max_transfer = min(supplies[i], demands[j])  # Maximum transfer allowed
                truck_transfer = np.random.randint(0, max_transfer + 1)  # Generate random truck transfer
                helicopter_transfer = max_transfer - truck_transfer  # Calculate helicopter transfer
                truck_transfers[i][j] = truck_transfer
        # Create a 2D list for helicopter transfers based on truck transfers
        helicopter_transfers = np.zeros((10, 11), dtype=int)
        for i in range(10):
            for j in range(11):
                max_transfer = min(supplies[i], demands[j])  # Maximum transfer allowed
                truck_transfer = truck_transfers[i][j]  # Get truck transfer value from previous step
                helicopter_transfer = max_transfer - truck_transfer  # Calculate helicopter transfer
                helicopter_transfers[i][j] = helicopter_transfer
        individual = [
            truck_transfers,
            helicopter_transfers
        ]
        population.append(individual)
    return population

def fitness_function(individual):
    truck_transfers = np.array(individual[0])
    helicopter_transfers = np.array(individual[1])

    total_cost = np.sum(distance_matrix * (helicopter_transfers / HELICOPTER_SPEED)) + np.sum(distance_matrix * (truck_transfers / TRUCK_SPEED))
    
    return total_cost

def selection(population, num_parents, fitnesses):
    # calculate total fitness of all individuals
    total_fitness = sum(fitnesses)
    # calculate relative fitness of each individual
    rel_fitness = [f/total_fitness for f in fitnesses]
    # generate probability intervals for each individual
    probs = [sum(rel_fitness[:i+1]) for i in range(len(rel_fitness))]
    # draw new population
    new_population = []
    for n in range(num_parents):
        r = random.random()
        for (i, individual) in enumerate(population):
            if r <= probs[i]:
                new_population.append(individual)
                break
    return new_population

def crossover(parents, num_offspring):
    offspring = []
    for _ in range(num_offspring):
        parent1, parent2 = random.sample(parents, 2)
        child = [parent1[0], parent2[1]]
        offspring.append(child)
    return offspring

def mutation(offspring, mutation_rate, bounds):
    for child in offspring:
        if random.random() < mutation_rate:
            child[0] = np.random.randint(bounds[0], bounds[1]+1, size=(10, 11))
            child[1] = np.random.randint(bounds[0], bounds[1]+1, size=(10, 11))

def genetic_algorithm(bounds, population_size, num_generations, num_parents, num_offspring, mutation_rate):
    population = create_population(population_size, bounds)

    for _ in range(num_generations):
        fitness_values = [fitness_function(individual) for individual in population]

        parents = selection(population, num_parents, fitness_values)
        offspring = crossover(parents, num_offspring)
        mutation(offspring, mutation_rate, bounds)

        population = parents + offspring

        best_fitness = min(fitness_values)
        best_individual = population[fitness_values.index(best_fitness)]

    return best_individual, population


# Parameters
bounds = (0, 200)
population_size = 100
num_generations = 50
num_parents = 50
num_offspring = 50
mutation_rate = 0.1

# Run the genetic algorithm
best_individual, population = genetic_algorithm(bounds, population_size, num_generations, num_parents, num_offspring, mutation_rate)

print("Best Individual(Truck):\n", best_individual[0],"\n")
print("Best Individual(Helicopter):\n", best_individual[1])
print("Best Fitness:", fitness_function(best_individual))

Best Individual(Truck):
 [[327 632 371 481 232 589 600 137 751 303 280]
 [129 323 145 111 165  77  71 463 222 563  65]
 [ 12 121 204 284 354 220 405 132 112  74  71]
 [ 26 296 301 186 208 267  36 212 214 258  17]
 [176  58  55 253  71 228 208  82 160  27 247]
 [107  74 131 160 112 111   5 150 175 180 151]
 [ 35  22 175 143  35  33 137  22  48  75 150]
 [133  60  71  96 125 144 126 147 117  59  97]
 [ 89  25  27 126  69 123  93 102   5  38  64]
 [ 33  68 129  13  20  92  95 102  55  28 129]]

Best Individual(Helicopter):
 [[792 187 789 159 742 243 636 101 513 236 604]
 [534 378 382 215 483 280 231 467  90 162 272]
 [ 52 364 244  18 279 438 435  11 169  58 233]
 [ 79   3  72 137 220 143  98 168 173 250  51]
 [  5  86  34  41  86   9 123  64  84 249 173]
 [180  86 133  93  68 208 107  99 150  24 218]
 [178  13  25 158 185 183 101  96 184 166 151]
 [ 32 176 126  73 172  51  53 162  83 165 138]
 [ 80 135  52 141 126  77 130 142  68 131  43]
 [141  58   6  11  79  73   1  25   3  77 106]]
Best Fitness: 216461.36000000004

In [32]:
def fitness_function(x, y):
    helicopter_allocation = x
    truck_allocation = y
    
    total_cost = 0

    for i in range(NUM_DISTRIBUTION_CENTERS):
        for j in range(NUM_AFFECTED_CITIES):
            if not road_blocked[i][j]:  # road is not blocked
                distance = distance_matrix[i][j]

                allocated_weight_helicopter = min(helicopter_allocation, demand_matrix[j][i])  # Access demand for affected city j and distribution center i
                allocated_weight_truck = min(truck_allocation, demand_matrix[j][i])  # Access demand for affected city j and distribution center i

                total_cost += distance * (allocated_weight_helicopter / HELICOPTER_SPEED) 
                total_cost += distance * (allocated_weight_truck / TRUCK_SPEED) 
    return total_cost

In [33]:
def simulated_annealing(function, bounds, n_iterations, initial_temp, cooling_rate):
    # Initialize a solution randomly within bounds
    current_sol = np.random.uniform(low=bounds[0], high=bounds[1], size=2)
    # Find the cost of the initalized cost
    current_cost = function(*current_sol)

    # At the beginning, initialized solution is best solution, and its cost is best cost
    best_sol, best_cost = current_sol, current_cost

    # Perform simulated annealing
    for i in range(n_iterations):
        # Generate a candidate solution by adding Gaussian perturbation to the current solution
        candidate_sol = current_sol + np.random.randn(2)
        # Stay withing bounds
        candidate_sol = np.clip(candidate_sol, bounds[0], bounds[1])
        # Cost of the candidate solution
        candidate_cost = function(*candidate_sol)

        # Candidate solution becomes current solution if it has a lower cost 
        # or with a certain probability based on temperature
        if candidate_cost < current_cost or np.random.rand() < np.exp((current_cost - candidate_cost) / initial_temp):
            current_sol, current_cost = candidate_sol, candidate_cost

            # Update the best solution if the candidate has a lower cost
            if candidate_cost < best_cost:
                best_sol, best_cost = candidate_sol, candidate_cost


        # Cool down the temperature
        initial_temp *= cooling_rate
#    Return best solution, best cost, and array that we store best solutions
    return best_sol, best_cost

bounds = (10, 500)
n_iterations = 5000
initial_temp = 100
cooling_rate = 0.9

best_allocation, best_fitness = simulated_annealing(fitness_function, bounds, n_iterations, initial_temp, cooling_rate)

print("Best Allocation:", best_allocation)
print("Best Fitness:", best_fitness)

Best Allocation: [10. 10.]
Best Fitness: 1121.5500000000002